[package]
name = "accounting-system"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.5.16", features = ["derive"] }
uuid = { version = "1.10", features = [ "v4" ] }
